### ISSUE TITLE
LOGIC: user service - check for min length of username and password

### ISSUE THREAD

**Issue by championswimmer** [scaleracademy/twitter-backend-node#6]
In `users.service.ts` in `createUser` we need field validations.

**Comment by alpha037** [comment]
@championswimmer, Hey, I'd like to work on this issue.

**Comment by championswimmer** [comment]
@alpha037 sure pick it up :)

**Comment by alpha037** [comment]
@championswimmer, hey, I've raised a [pull request](https://github.com/scaleracademy/twitter-backend-node/pull/9) for this.
